services:
  backend:
    environment:
      NODE_ENV: development
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/uploads:/app/uploads
    working_dir: /app
    command: sh -c "npm install && npm run dev"

  frontend:
    environment:
      NODE_ENV: development
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    working_dir: /app
    image: node:18-alpine
    command: sh -c "npm install && npm run dev -- --host"

