import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation files
const translations = {
  en: {
    // Admin Dashboard
    'admin.dashboard.title': 'Admin Dashboard',
    'admin.dashboard.welcome': 'Welcome, {name}',
    'admin.dashboard.loading': 'Loading admin dashboard...',
    'admin.dashboard.loading.stats': 'Loading dashboard statistics...',
    'admin.dashboard.overview': 'Dashboard Overview',
    'admin.dashboard.description': 'System statistics and health monitoring',
    'admin.dashboard.retry': 'Retry',
    'admin.dashboard.failed.load': 'Failed to load dashboard statistics',
    'admin.badge': 'Admin',
    
    // Admin Stats
    'admin.stats.total.users': 'Total Users',
    'admin.stats.active.users': 'Active Users',
    'admin.stats.total.plans': 'Total Plans',
    'admin.stats.active.subscriptions': 'Active Subscriptions',
    'admin.stats.total.jobs': 'Total Jobs',
    'admin.stats.job.applications': 'Job Applications',
    'admin.stats.total.revenue': 'Total Revenue',
    'admin.stats.monthly.revenue': 'Monthly Revenue',
    'admin.stats.from.last.month': 'from last month',
    
    // Admin System Health
    'admin.system.health': 'System Health',
    'admin.system.server.uptime': 'Server Uptime',
    'admin.system.memory.usage': 'Memory Usage',
    'admin.system.node.version': 'Node Version',
    'admin.system.platform': 'Platform',
    
    // Admin Recent Activity
    'admin.recent.activity': 'Recent Activity',
    'admin.latest.users': 'Latest Users',
    'admin.latest.jobs': 'Latest Jobs',
    'admin.unknown': 'Unknown',
    
    // Language selector
    'language.selector': 'Language',
    'language.english': 'English',
    'language.turkish': 'Türkçe',
    
    // Navbar
    'nav.browse.memberships': 'Browse Memberships',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.dashboard': 'Dashboard',
    'nav.membership': 'Membership',
    'nav.people': 'People',
    'nav.career.center': 'Career Center',
    'nav.admin': 'Admin',
    'nav.view.profile': 'View Profile',
    'nav.edit.profile': 'Edit Profile',
    'nav.logout': 'Logout',
    'nav.followers': 'Followers',
    'nav.following': 'Following',
    'nav.memberships': 'Memberships',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome back, {name}!',
    'dashboard.recent.activity': 'Recent Activity',
    'dashboard.quick.actions': 'Quick Actions',
    'dashboard.stats': 'Statistics',
    'dashboard.no.posts': 'No posts yet. Create your first post above!',
    'dashboard.no.memberships': "You don't have any active memberships yet.",
    'dashboard.browse.all.memberships': 'Browse All Memberships',
    'dashboard.membership.plan': 'Membership Plan',
    'dashboard.organization': 'Organization',
    
    // Login/Register
    'auth.login.title': 'Login',
    'auth.register.title': 'Register',
    'auth.forgot.password': 'Forgot Password',
    'auth.reset.password': 'Reset Password',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirm.password': 'Confirm Password',
    'auth.first.name': 'First Name',
    'auth.last.name': 'Last Name',
    'auth.username': 'Username',
    'auth.remember.me': 'Remember me',
    'auth.login.button': 'Login',
    'auth.register.button': 'Register',
    'auth.reset.button': 'Reset Password',
    'auth.send.reset': 'Send Reset Email',
    'auth.dont.have.account': "Don't have an account?",
    'auth.have.account': 'Already have an account?',
    'auth.forgot.password.link': 'Forgot your password?',
    
    // Profile
    'profile.title': 'Profile',
    'profile.edit': 'Edit Profile',
    'profile.save': 'Save Changes',
    'profile.cancel': 'Cancel',
    'profile.about': 'About',
    'profile.location': 'Location',
    'profile.website': 'Website',
    'profile.bio': 'Bio',
    'profile.skills': 'Skills',
    'profile.experience': 'Experience',
    'profile.education': 'Education',
    
    // Membership
    'membership.title': 'Membership',
    'membership.plans': 'Membership Plans',
    'membership.current': 'Current Membership',
    'membership.upgrade': 'Upgrade',
    'membership.downgrade': 'Downgrade',
    'membership.cancel': 'Cancel Membership',
    'membership.features': 'Features',
    'membership.benefits': 'Benefits',
    'membership.price': 'Price',
    'membership.duration': 'Duration',
    'membership.dashboard': 'Dashboard',
    'membership.payments': 'Payments',
    'membership.scheduled.payments': 'Scheduled Payments',
    'membership.debts': 'Debts',
    'membership.reminders': 'Reminders',
    'membership.applications': 'Applications',
    'membership.settings': 'Settings',
    'membership.coupons': 'Coupons',
    'membership.application.forms': 'Application Forms',
    'membership.application.form.builder': 'Application Form Builder',
    'membership.digital.card': 'Digital Card',
    'membership.payment.info': 'Payment Info',
    
    // Membership Dashboard
    'membership.dashboard.loading': 'Loading dashboard...',
    'membership.dashboard.error': 'Error loading dashboard: {error}',
    'membership.dashboard.retry': 'Retry',
    'membership.dashboard.loading.data': 'Loading dashboard data...',
    'membership.dashboard.total.subscriptions': 'Total Subscriptions',
    'membership.dashboard.active.subscriptions': 'Active Subscriptions',
    'membership.dashboard.past.due': 'Past Due',
    'membership.dashboard.total.revenue': 'Total Revenue',
    'membership.dashboard.this.month': 'this month',
    'membership.dashboard.of.total': 'of total',
    'membership.dashboard.subscription.trends': 'Subscription Trends',
    'membership.dashboard.revenue.trends': 'Revenue Trends',
    'membership.dashboard.new.subscriptions': 'New Subscriptions',
    'membership.dashboard.revenue': 'Revenue',
    'membership.dashboard.recent.payments': 'Recent Payments',
    'membership.dashboard.date': 'Date',
    'membership.dashboard.member': 'Member',
    'membership.dashboard.plan': 'Plan',
    'membership.dashboard.amount': 'Amount',
    'membership.dashboard.status': 'Status',
    'membership.dashboard.no.recent.payments': 'No recent payments',
    
    // Membership Plans
    'membership.plans.title': 'Membership Plans',
    'membership.plans.add.plan': 'Add Plan',
    'membership.plans.search.placeholder': 'Search plans...',
    'membership.plans.all.plans': 'All Plans',
    'membership.plans.active.only': 'Active Only',
    'membership.plans.inactive.only': 'Inactive Only',
    'membership.plans.edit.plan': 'Edit Plan',
    'membership.plans.add.plan': 'Add Plan',
    'membership.plans.plan.name': 'Plan Name',
    'membership.plans.plan.name.placeholder': 'e.g., Basic Plan',
    'membership.plans.description': 'Description',
    'membership.plans.description.placeholder': 'Plan description...',
    'membership.plans.plan.type': 'Plan Type',
    'membership.plans.paid.plan': 'Paid Plan',
    'membership.plans.free.plan': 'Free Plan',
    'membership.plans.fee': 'Fee',
    'membership.plans.fee.placeholder': '0.00',
    'membership.plans.free': 'Free',
    'membership.plans.renewal.interval': 'Renewal Interval',
    'membership.plans.monthly': 'Monthly',
    'membership.plans.quarterly': 'Quarterly',
    'membership.plans.yearly': 'Yearly',
    'membership.plans.one.time': 'One-time',
    'membership.plans.max.members': 'Max Members (optional)',
    'membership.plans.max.members.placeholder': 'Leave empty for unlimited',
    'membership.plans.application.form': 'Application Form',
    'membership.plans.use.default.form': 'Use Organization Default Form',
    'membership.plans.use.custom.form': 'Use Custom Form',
    'membership.plans.select.custom.form': 'Select Custom Application Form',
    'membership.plans.no.forms.available': 'No published application forms available. Please create and publish a form first.',
    'membership.plans.create.form': 'Create Application Form',
    'membership.plans.loading.forms': 'Loading forms...',
    'membership.plans.select.form': 'Select a form...',
    'membership.plans.form.help': 'Choose a custom application form that will be used when users apply for this plan. Only published forms are available for selection. Click the refresh button to update the list.',
    'membership.plans.benefits': 'Benefits',
    'membership.plans.enter.benefit': 'Enter benefit...',
    'membership.plans.add.benefit': 'Add Benefit',
    'membership.plans.cancel': 'Cancel',
    'membership.plans.save.plan': 'Save Plan',
    'membership.plans.saving': 'Saving...',
    'membership.plans.active': 'Active',
    'membership.plans.inactive': 'Inactive',
    'membership.plans.delete.plan': 'Delete Plan',
    'membership.plans.confirm.delete': 'Are you sure you want to delete this plan? This cannot be undone.',
    'membership.plans.delete': 'Delete',
    'membership.plans.no.plans.found': 'No plans found',
    'membership.plans.create.first.plan': 'Create your first plan',
    'membership.plans.benefits.title': 'Benefits:',
    'membership.plans.active.subscriptions': 'Active',
    'membership.plans.total.subscriptions': 'Total',
    'membership.plans.limit': 'Limit',
    
    // Career Center
    'career.title': 'Career Center',
    'career.jobs': 'Job Listings',
    'career.apply': 'Apply',
    'career.saved': 'Saved Jobs',
    'career.applications': 'My Applications',
    'career.job.title': 'Job Title',
    'career.company': 'Company',
    'career.location': 'Location',
    'career.salary': 'Salary',
    'career.type': 'Job Type',
    'career.description': 'Description',
    'career.requirements': 'Requirements',
    'career.choose.role': 'Choose your role to get started',
    'career.job.seeker': 'Job Seeker',
    'career.employer': 'Employer',
    
    // Career Individual Dashboard
    'career.individual.browse.jobs': 'Browse Jobs',
    'career.individual.my.applications': 'My Applications',
    'career.individual.saved.jobs': 'Saved Jobs',
    'career.individual.career.profile': 'Career Profile',
    'career.individual.select.page': 'Select Page',
    
    // Career Company Dashboard
    'career.company.job.postings': 'Job Postings',
    'career.company.applications': 'Applications',
    'career.company.analytics': 'Analytics',
    'career.company.select.page': 'Select Page',
    'career.company.actions': 'Actions',
    'career.company.job.status': 'Job Status',
    'career.company.activate.job': 'Activate Job',
    'career.company.activate.job.desc': 'Make job visible to candidates',
    'career.company.pause.job': 'Pause Job',
    'career.company.pause.job.desc': 'Temporarily hide from candidates',
    'career.company.close.job': 'Close Job',
    'career.company.close.job.desc': 'Stop accepting applications',
    'career.company.edit.job.details': 'Edit Job Details',
    'career.company.view.applications': 'View Applications',
    'career.company.edit.job.posting': 'Edit Job Posting',
    'career.company.create.new.job.posting': 'Create New Job Posting',
    'career.company.cancel': 'Cancel',
    'career.company.loading.jobs': 'Loading your job postings...',
    'career.company.no.job.postings': 'No job postings yet',
    'career.company.create.first.job': 'Create your first job posting to get started.',
    'career.company.post.job': 'Post a Job',
    'career.company.your.job.postings': 'Your Job Postings ({count} active)',
    'career.company.post.new.job': 'Post New Job',
    'career.company.posted': 'Posted',
    'career.company.applications': 'applications',
    'career.company.remote': 'Remote',
    'career.company.salary.not.specified': 'Salary not specified',
    'career.company.previous': 'Previous',
    'career.company.next': 'Next',
    'career.company.filter.by.status': 'Filter by Status',
    'career.company.all.status': 'All Status',
    'career.company.pending': 'Pending',
    'career.company.reviewing': 'Reviewing',
    'career.company.interview': 'Interview',
    'career.company.accepted': 'Accepted',
    'career.company.rejected': 'Rejected',
    'career.company.filter.by.job': 'Filter by Job',
    'career.company.all.jobs': 'All Jobs',
    'career.company.loading.applications': 'Loading applications...',
    'career.company.no.applications': 'No applications yet',
    'career.company.applications.desc': 'Applications for your job postings will appear here.',
    'career.company.applied.for': 'Applied for',
    'career.company.email': 'Email',
    'career.company.applied': 'Applied',
    'career.company.cover.letter': 'Cover Letter',
    'career.company.notes': 'Notes',
    'career.company.view.resume': 'View Resume',
    
    // Users
    'users.title': 'People',
    'users.search': 'Search People',
    'users.follow': 'Follow',
    'users.unfollow': 'Unfollow',
    'users.message': 'Message',
    'users.connect': 'Connect',
    'users.mutual.connections': 'Mutual Connections',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.submit': 'Submit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
    'common.required': 'Required',
    'common.optional': 'Optional',
    
    // Membership Application
    'membership.apply.title': 'Apply for Membership',
    'membership.apply.organization': 'Organization',
    'membership.apply.fee': 'Fee',
    'membership.apply.application.fee': 'Application Fee',
    'membership.apply.form.not.available': 'Form Not Available',
    'membership.apply.form.not.available.desc': 'The application form for this membership is not currently available.',
    'membership.apply.plan.creator.error': 'You cannot apply for a plan that you created. Plan creators are automatically considered members.',
    'membership.apply.select.field': 'Select {field}',
    'membership.apply.enter.field': 'Enter {field}',
    
    // Plan Details
    'plan.details.title': 'Plan Details',
    'plan.details.description': 'Description',
    'plan.details.benefits': 'Benefits',
    'plan.details.renewal.interval': 'Renewal Interval',
    'plan.details.status': 'Status',
    'plan.details.max.members': 'Max Members',
    'plan.details.active': 'Active',
    'plan.details.inactive': 'Inactive',
    'plan.details.free': 'Free',
    'plan.details.per.month': 'per month',
    'plan.details.per.quarter': 'per quarter',
    'plan.details.per.year': 'per year',
    'plan.details.one.time': 'one-time',
    'plan.details.no.description': 'No description available.',
    
    // Navigation
    'nav.language': 'Language',
    
    // Applications
    'applications.title': 'Membership Applications',
    'applications.loading': 'Loading applications...',
    'applications.search.placeholder': 'Search by name, email...',
    'applications.all.statuses': 'All Statuses',
    'applications.pending': 'Pending',
    'applications.approved': 'Approved',
    'applications.rejected': 'Rejected',
    'applications.date.applied': 'Date Applied',
    'applications.name': 'Name',
    'applications.email': 'Email',
    'applications.phone': 'Phone',
    'applications.plan': 'Plan',
    'applications.student.id': 'Student ID',
    'applications.status': 'Status',
    'applications.actions': 'Actions',
    'applications.approve': 'Approve',
    'applications.reject': 'Reject',
    'applications.view': 'View',
    'applications.delete': 'Delete',
    'applications.no.applications': 'No applications found',
    'applications.join.organization': 'Join an Organization',
    'applications.join.description': 'You need to be a member of an organization to view membership applications.',
    'applications.no.organizations': 'No organizations available to join.',
    'applications.visit.website': 'Visit Website',
    'applications.join.organization.button': 'Join Organization',
    'applications.joining': 'Joining...',
    'applications.successfully.joined': 'Successfully joined organization! You can now view applications.',
    'applications.error.joining': 'Error joining organization: {error}',
    'applications.view.details': 'View Application Details',
    'applications.approve.application': 'Approve Application',
    'applications.reject.application': 'Reject Application',
    'applications.basic.information': 'Basic Information',
    'applications.not.provided': 'Not provided',
    'applications.custom.form.data': 'Custom Form Data',
    'applications.payment.information': 'Payment Information',
    'applications.payment.method': 'Payment Method',
    'applications.amount': 'Amount',
    'applications.transaction.id': 'Transaction ID',
    'applications.processed': 'Processed',
    'applications.approval.notes': 'Approval Notes (Optional)',
    'applications.rejection.notes': 'Rejection Notes (Optional)',
    'applications.add.notes': 'Add notes about this {type}...',
    'applications.notes.help': 'Notes will be saved with the application and can be viewed later.',
    'applications.action': 'Action',
    'applications.approve.and.create': 'Approve application for {name} and create user account',
    'applications.reject.application.for': 'Reject application for {name}',
    'applications.close': 'Close',
    'applications.cancel': 'Cancel',
    'applications.approve.application.button': 'Approve Application',
    'applications.reject.application.button': 'Reject Application',
    'applications.page': 'Page {current} of {total}',
    
    // Payments
    'payments.title': 'Payments',
    'payments.add.payment': 'Add Payment',
    'payments.loading': 'Loading payments...',
    'payments.search.placeholder': 'Search by name, reference number...',
    'payments.all.statuses': 'All Statuses',
    'payments.completed': 'Completed',
    'payments.failed': 'Failed',
    'payments.refunded': 'Refunded',
    'payments.payment.date': 'Payment Date',
    'payments.full.name': 'Full Name',
    'payments.payment.method': 'Payment Method',
    'payments.identifier': 'Identifier',
    'payments.reference.number': 'Reference Number',
    'payments.edit.payment': 'Edit Payment',
    'payments.delete.payment': 'Delete Payment',
    'payments.no.payments': 'No payments found',
    'payments.edit.payment.modal': 'Edit Payment',
    'payments.add.payment.modal': 'Add Payment',
    'payments.user': 'User',
    'payments.select.user': 'Select User',
    'payments.select.plan': 'Select Plan',
    'payments.payment.date.label': 'Payment Date',
    'payments.identifier.placeholder': 'Transaction ID',
    'payments.reference.number.placeholder': 'Reference number',
    'payments.notes': 'Notes',
    'payments.additional.notes': 'Additional notes...',
    'payments.save.payment': 'Save Payment',
    'payments.saving': 'Saving...',
    'payments.error.saving': 'Error saving payment: {error}',
    'payments.error.deleting': 'Error deleting payment: {error}',
    'payments.confirm.delete': 'Are you sure you want to delete this payment?',
    'payments.cash': 'Cash',
    'payments.bank.transfer': 'Bank Transfer',
    'payments.credit.card': 'Credit Card',
    'payments.debit.card': 'Debit Card',
    'payments.mobile.payment': 'Mobile Payment',
    'payments.other': 'Other',
    
    // Scheduled Payments
    'scheduled.payments.title': 'Scheduled Payments',
    'scheduled.payments.add': 'Add Scheduled Payment',
    'scheduled.payments.loading': 'Loading scheduled payments...',
    'scheduled.payments.no.payments': 'No scheduled payments configured',
    'scheduled.payments.create.first': 'Create Your First Scheduled Payment',
    'scheduled.payments.scheduled.date': 'Scheduled Date',
    'scheduled.payments.frequency': 'Frequency',
    'scheduled.payments.one.time': 'One Time',
    'scheduled.payments.monthly': 'Monthly',
    'scheduled.payments.quarterly': 'Quarterly',
    'scheduled.payments.yearly': 'Yearly',
    'scheduled.payments.delete.title': 'Delete scheduled payment',
    'scheduled.payments.add.modal': 'Add Scheduled Payment',
    'scheduled.payments.amount': 'Amount',
    'scheduled.payments.scheduled.date.time': 'Scheduled Date & Time',
    'scheduled.payments.description': 'Description',
    'scheduled.payments.description.placeholder': 'Enter payment description...',
    'scheduled.payments.associated.plan': 'Associated Plan (Optional)',
    'scheduled.payments.select.plan': 'Select a plan',
    'scheduled.payments.cancel': 'Cancel',
    'scheduled.payments.create': 'Create Scheduled Payment',
    'scheduled.payments.creating': 'Creating...',
    'scheduled.payments.confirm.delete': 'Are you sure you want to delete this scheduled payment?',
    
    // Debts
    'debts.title': 'Debts & Outstanding Balances',
    'debts.total.outstanding': 'Total Outstanding',
    'debts.add.debt': 'Add Debt',
    'debts.loading': 'Loading debts...',
    'debts.no.debts': 'No debts recorded',
    'debts.add.first.debt': 'Add Your First Debt',
    'debts.issued.on': 'Issued On',
    'debts.type': 'Type',
    'debts.subscription': 'Subscription',
    'debts.fee': 'Fee',
    'debts.penalty': 'Penalty',
    'debts.other': 'Other',
    'debts.outstanding': 'Outstanding',
    'debts.paid': 'Paid',
    'debts.written.off': 'Written Off',
    'debts.manual.entry': 'Manual',
    'debts.mark.as.paid': 'Mark as paid',
    'debts.write.off': 'Write off',
    'debts.delete.debt': 'Delete debt',
    'debts.add.modal': 'Add New Debt',
    'debts.amount': 'Amount',
    'debts.description': 'Description',
    'debts.description.placeholder': 'Enter debt description...',
    'debts.debt.type': 'Debt Type',
    'debts.issue.date': 'Issue Date',
    'debts.manual.entry.label': 'Manual Entry',
    'debts.manual.entry.help': 'Check this if this debt was entered manually rather than generated automatically',
    'debts.cancel': 'Cancel',
    'debts.create.debt': 'Create Debt',
    'debts.creating': 'Creating...',
    'debts.confirm.delete': 'Are you sure you want to delete this debt?',
    
    // Reminders
    'reminders.title': 'Reminders & Notifications',
    'reminders.add.reminder': 'Add Reminder',
    'reminders.loading': 'Loading reminders...',
    'reminders.no.reminders': 'No reminders configured',
    'reminders.create.first': 'Create Your First Reminder',
    'reminders.scheduled': 'Scheduled',
    'reminders.recipient': 'Recipient',
    'reminders.send.now': 'Send now',
    'reminders.delete.reminder': 'Delete reminder',
    'reminders.add.modal': 'Add New Reminder',
    'reminders.reminder.name': 'Reminder Name',
    'reminders.reminder.name.placeholder': 'Enter reminder name...',
    'reminders.reminder.type': 'Reminder Type',
    'reminders.renewal.reminder': 'Renewal Reminder',
    'reminders.payment.due': 'Payment Due',
    'reminders.overdue.notice': 'Overdue Notice',
    'reminders.welcome.message': 'Welcome Message',
    'reminders.custom.reminder': 'Custom Reminder',
    'reminders.reminder.date.time': 'Reminder Date & Time',
    'reminders.message': 'Message',
    'reminders.message.placeholder': 'Enter reminder message...',
    'reminders.cancel': 'Cancel',
    'reminders.create.reminder': 'Create Reminder',
    'reminders.creating': 'Creating...',
    'reminders.confirm.delete': 'Are you sure you want to delete this reminder?',
    
    // Membership Settings
    'settings.title': 'Membership Settings',
    'settings.general.settings': 'General Settings',
    'settings.auto.approve': 'Auto-approve applications',
    'settings.enable.form': 'Enable application form',
    'settings.allow.bank.transfers': 'Allow bank transfers',
    'settings.invoice.text': 'Invoice Text',
    'settings.invoice.text.placeholder': 'Custom text to appear on invoices...',
    'settings.email.notifications': 'Email Notifications',
    'settings.new.application.notifications': 'New application notifications',
    'settings.payment.received.notifications': 'Payment received notifications',
    'settings.subscription.expiring.notifications': 'Subscription expiring notifications',
    'settings.save.settings': 'Save Settings',
    'settings.saved.successfully': 'Settings saved successfully!',
    
    // Coupons
    'coupons.title': 'Coupons & Discounts',
    'coupons.add.coupon': 'Add Coupon',
    'coupons.loading': 'Loading coupons...',
    'coupons.no.coupons': 'No coupons configured',
    'coupons.create.first': 'Create Your First Coupon',
    'coupons.discount': 'Discount',
    'coupons.redemptions': 'Redemptions',
    'coupons.expires': 'Expires',
    'coupons.no.expiry': 'No expiry',
    'coupons.activate': 'Activate',
    'coupons.deactivate': 'Deactivate',
    'coupons.delete.coupon': 'Delete coupon',
    'coupons.add.modal': 'Add New Coupon',
    'coupons.coupon.name': 'Coupon Name',
    'coupons.coupon.name.placeholder': 'Enter coupon name...',
    'coupons.coupon.code': 'Coupon Code',
    'coupons.coupon.code.placeholder': 'Enter coupon code...',
    'coupons.generate': 'Generate',
    'coupons.discount.amount': 'Discount Amount',
    'coupons.discount.type': 'Discount Type',
    'coupons.percentage': 'Percentage (%)',
    'coupons.fixed.amount': 'Fixed Amount ($)',
    'coupons.max.redemptions': 'Max Redemptions',
    'coupons.max.redemptions.placeholder': 'Leave empty for unlimited',
    'coupons.max.redemptions.help': 'Leave empty for unlimited redemptions',
    'coupons.expiry.date': 'Expiry Date',
    'coupons.expiry.date.help': 'Leave empty for no expiry date',
    'coupons.cancel': 'Cancel',
    'coupons.create.coupon': 'Create Coupon',
    'coupons.creating': 'Creating...',
    'coupons.confirm.delete': 'Are you sure you want to delete this coupon?',
    'coupons.inactive': 'Inactive',
    'coupons.expired': 'Expired',
    'coupons.maxed.out': 'Maxed Out',
    'coupons.active': 'Active',
    
    // Application Forms
    'forms.title': 'Application Forms',
    'forms.create.form': 'Create Form',
    'forms.loading': 'Loading application forms...',
    'forms.join.organization': 'Join an Organization',
    'forms.join.description': 'You need to join an organization to create and manage application forms.',
    'forms.no.organizations': 'No organizations available to join.',
    'forms.join.organization.button': 'Join Organization',
    'forms.joining': 'Joining...',
    'forms.failed.to.join': 'Failed to join organization: {error}',
    'forms.view.form': 'View Form',
    'forms.edit.form': 'Edit Form',
    'forms.unpublish.form': 'Unpublish Form',
    'forms.publish.form': 'Publish Form',
    'forms.delete.form': 'Delete Form',
    'forms.fields': 'Fields',
    'forms.created': 'Created',
    'forms.updated': 'Updated',
    'forms.form.fields': 'Form Fields',
    'forms.more': 'more',
    'forms.no.forms': 'No application forms found',
    'forms.create.first': 'Create your first form',
    'forms.edit.modal': 'Edit Form',
    'forms.create.modal': 'Create Form',
    'forms.form.title': 'Form Title',
    'forms.form.title.placeholder': 'e.g., Gym Membership Application',
    'forms.description': 'Description',
    'forms.description.placeholder': 'Form description...',
    'forms.cancel': 'Cancel',
    'forms.save.form': 'Save Form',
    'forms.saving': 'Saving...',
    'forms.error.saving': 'Error saving form: {error}',
    'forms.error.deleting': 'Error deleting form: {error}',
    'forms.error.publishing': 'Error publishing form: {error}',
    'forms.error.unpublishing': 'Error unpublishing form: {error}',
    'forms.confirm.delete': 'Are you sure you want to delete this form? This cannot be undone.',
    'forms.published': 'Published',
    'forms.draft': 'Draft',
    'forms.view.modal.title': 'View Application Form: {title}',
    'forms.close': 'Close',
    'forms.description.section': 'Description',
    'forms.status.section': 'Status',
    'forms.fields.section': 'Form Fields ({count})',
    'forms.no.fields': 'No fields defined for this form.',
    'forms.form.information': 'Form Information',
    'forms.created.label': 'Created',
    'forms.last.updated': 'Last Updated',
    'forms.organization': 'Organization',
    'forms.edit.form.button': 'Edit Form',
    'forms.required': 'Required',
    'forms.placeholder': 'Placeholder: {placeholder}',
    'forms.options': 'Options: {options}',
  },
  tr: {
    // Admin Dashboard
    'admin.dashboard.title': 'Yönetici Paneli',
    'admin.dashboard.welcome': 'Hoş geldiniz, {name}',
    'admin.dashboard.loading': 'Yönetici paneli yükleniyor...',
    'admin.dashboard.loading.stats': 'Panel istatistikleri yükleniyor...',
    'admin.dashboard.overview': 'Panel Genel Bakış',
    'admin.dashboard.description': 'Sistem istatistikleri ve sağlık izleme',
    'admin.dashboard.retry': 'Tekrar Dene',
    'admin.dashboard.failed.load': 'Panel istatistikleri yüklenemedi',
    'admin.badge': 'Yönetici',
    
    // Admin Stats
    'admin.stats.total.users': 'Toplam Kullanıcı',
    'admin.stats.active.users': 'Aktif Kullanıcı',
    'admin.stats.total.plans': 'Toplam Plan',
    'admin.stats.active.subscriptions': 'Aktif Abonelik',
    'admin.stats.total.jobs': 'Toplam İş',
    'admin.stats.job.applications': 'İş Başvurusu',
    'admin.stats.total.revenue': 'Toplam Gelir',
    'admin.stats.monthly.revenue': 'Aylık Gelir',
    'admin.stats.from.last.month': 'geçen aydan',
    
    // Admin System Health
    'admin.system.health': 'Sistem Sağlığı',
    'admin.system.server.uptime': 'Sunucu Çalışma Süresi',
    'admin.system.memory.usage': 'Bellek Kullanımı',
    'admin.system.node.version': 'Node Sürümü',
    'admin.system.platform': 'Platform',
    
    // Admin Recent Activity
    'admin.recent.activity': 'Son Aktiviteler',
    'admin.latest.users': 'Son Kullanıcılar',
    'admin.latest.jobs': 'Son İşler',
    'admin.unknown': 'Bilinmeyen',
    
    // Language selector
    'language.selector': 'Dil',
    'language.english': 'English',
    'language.turkish': 'Türkçe',
    
    // Navbar
    'nav.browse.memberships': 'Üyelikleri Gözat',
    'nav.login': 'Giriş Yap',
    'nav.register': 'Kayıt Ol',
    'nav.dashboard': 'Panel',
    'nav.membership': 'Üyelik',
    'nav.people': 'Kişiler',
    'nav.career.center': 'Kariyer Merkezi',
    'nav.admin': 'Yönetici',
    'nav.view.profile': 'Profili Görüntüle',
    'nav.edit.profile': 'Profili Düzenle',
    'nav.logout': 'Çıkış Yap',
    'nav.followers': 'Takipçiler',
    'nav.following': 'Takip Edilenler',
    'nav.memberships': 'Üyelikler',
    
    // Dashboard
    'dashboard.title': 'Panel',
    'dashboard.welcome': 'Tekrar hoş geldiniz, {name}!',
    'dashboard.recent.activity': 'Son Aktiviteler',
    'dashboard.quick.actions': 'Hızlı İşlemler',
    'dashboard.stats': 'İstatistikler',
    'dashboard.no.posts': 'Henüz gönderi yok. Yukarıdan ilk gönderinizi oluşturun!',
    'dashboard.no.memberships': 'Henüz aktif üyeliğiniz yok.',
    'dashboard.browse.all.memberships': 'Tüm Üyelikleri Gözat',
    'dashboard.membership.plan': 'Üyelik Planı',
    'dashboard.organization': 'Organizasyon',
    
    // Login/Register
    'auth.login.title': 'Giriş Yap',
    'auth.register.title': 'Kayıt Ol',
    'auth.forgot.password': 'Şifremi Unuttum',
    'auth.reset.password': 'Şifre Sıfırla',
    'auth.email': 'E-posta',
    'auth.password': 'Şifre',
    'auth.confirm.password': 'Şifreyi Onayla',
    'auth.first.name': 'Ad',
    'auth.last.name': 'Soyad',
    'auth.username': 'Kullanıcı Adı',
    'auth.remember.me': 'Beni hatırla',
    'auth.login.button': 'Giriş Yap',
    'auth.register.button': 'Kayıt Ol',
    'auth.reset.button': 'Şifre Sıfırla',
    'auth.send.reset': 'Sıfırlama E-postası Gönder',
    'auth.dont.have.account': 'Hesabınız yok mu?',
    'auth.have.account': 'Zaten hesabınız var mı?',
    'auth.forgot.password.link': 'Şifrenizi mi unuttunuz?',
    
    // Profile
    'profile.title': 'Profil',
    'profile.edit': 'Profili Düzenle',
    'profile.save': 'Değişiklikleri Kaydet',
    'profile.cancel': 'İptal',
    'profile.about': 'Hakkında',
    'profile.location': 'Konum',
    'profile.website': 'Web Sitesi',
    'profile.bio': 'Biyografi',
    'profile.skills': 'Yetenekler',
    'profile.experience': 'Deneyim',
    'profile.education': 'Eğitim',
    
    // Membership
    'membership.title': 'Üyelik',
    'membership.plans': 'Üyelik Planları',
    'membership.current': 'Mevcut Üyelik',
    'membership.upgrade': 'Yükselt',
    'membership.downgrade': 'Düşür',
    'membership.cancel': 'Üyeliği İptal Et',
    'membership.features': 'Özellikler',
    'membership.benefits': 'Avantajlar',
    'membership.price': 'Fiyat',
    'membership.duration': 'Süre',
    'membership.dashboard': 'Panel',
    'membership.payments': 'Ödemeler',
    'membership.scheduled.payments': 'Planlanmış Ödemeler',
    'membership.debts': 'Borçlar',
    'membership.reminders': 'Hatırlatıcılar',
    'membership.applications': 'Başvurular',
    'membership.settings': 'Ayarlar',
    'membership.coupons': 'Kuponlar',
    'membership.application.forms': 'Başvuru Formları',
    'membership.application.form.builder': 'Başvuru Formu Oluşturucu',
    'membership.digital.card': 'Dijital Kart',
    'membership.payment.info': 'Ödeme Bilgileri',
    
    // Membership Dashboard
    'membership.dashboard.loading': 'Panel yükleniyor...',
    'membership.dashboard.error': 'Panel yüklenirken hata: {error}',
    'membership.dashboard.retry': 'Tekrar Dene',
    'membership.dashboard.loading.data': 'Panel verileri yükleniyor...',
    'membership.dashboard.total.subscriptions': 'Toplam Abonelik',
    'membership.dashboard.active.subscriptions': 'Aktif Abonelik',
    'membership.dashboard.past.due': 'Vadesi Geçmiş',
    'membership.dashboard.total.revenue': 'Toplam Gelir',
    'membership.dashboard.this.month': 'bu ay',
    'membership.dashboard.of.total': 'toplamın',
    'membership.dashboard.subscription.trends': 'Abonelik Trendleri',
    'membership.dashboard.revenue.trends': 'Gelir Trendleri',
    'membership.dashboard.new.subscriptions': 'Yeni Abonelikler',
    'membership.dashboard.revenue': 'Gelir',
    'membership.dashboard.recent.payments': 'Son Ödemeler',
    'membership.dashboard.date': 'Tarih',
    'membership.dashboard.member': 'Üye',
    'membership.dashboard.plan': 'Plan',
    'membership.dashboard.amount': 'Tutar',
    'membership.dashboard.status': 'Durum',
    'membership.dashboard.no.recent.payments': 'Son ödeme yok',
    
    // Membership Plans
    'membership.plans.title': 'Üyelik Planları',
    'membership.plans.add.plan': 'Plan Ekle',
    'membership.plans.search.placeholder': 'Plan ara...',
    'membership.plans.all.plans': 'Tüm Planlar',
    'membership.plans.active.only': 'Sadece Aktif',
    'membership.plans.inactive.only': 'Sadece Pasif',
    'membership.plans.edit.plan': 'Planı Düzenle',
    'membership.plans.add.plan': 'Plan Ekle',
    'membership.plans.plan.name': 'Plan Adı',
    'membership.plans.plan.name.placeholder': 'örn., Temel Plan',
    'membership.plans.description': 'Açıklama',
    'membership.plans.description.placeholder': 'Plan açıklaması...',
    'membership.plans.plan.type': 'Plan Türü',
    'membership.plans.paid.plan': 'Ücretli Plan',
    'membership.plans.free.plan': 'Ücretsiz Plan',
    'membership.plans.fee': 'Ücret',
    'membership.plans.fee.placeholder': '0.00',
    'membership.plans.free': 'Ücretsiz',
    'membership.plans.renewal.interval': 'Yenileme Aralığı',
    'membership.plans.monthly': 'Aylık',
    'membership.plans.quarterly': 'Çeyrek Yıllık',
    'membership.plans.yearly': 'Yıllık',
    'membership.plans.one.time': 'Tek Seferlik',
    'membership.plans.max.members': 'Maksimum Üye (opsiyonel)',
    'membership.plans.max.members.placeholder': 'Sınırsız için boş bırakın',
    'membership.plans.application.form': 'Başvuru Formu',
    'membership.plans.use.default.form': 'Organizasyon Varsayılan Formunu Kullan',
    'membership.plans.use.custom.form': 'Özel Form Kullan',
    'membership.plans.select.custom.form': 'Özel Başvuru Formu Seç',
    'membership.plans.no.forms.available': 'Yayınlanmış başvuru formu yok. Lütfen önce bir form oluşturup yayınlayın.',
    'membership.plans.create.form': 'Başvuru Formu Oluştur',
    'membership.plans.loading.forms': 'Formlar yükleniyor...',
    'membership.plans.select.form': 'Form seçin...',
    'membership.plans.form.help': 'Kullanıcılar bu plana başvurduğunda kullanılacak özel başvuru formunu seçin. Sadece yayınlanmış formlar seçilebilir. Listeyi güncellemek için yenile butonuna tıklayın.',
    'membership.plans.benefits': 'Avantajlar',
    'membership.plans.enter.benefit': 'Avantaj girin...',
    'membership.plans.add.benefit': 'Avantaj Ekle',
    'membership.plans.cancel': 'İptal',
    'membership.plans.save.plan': 'Planı Kaydet',
    'membership.plans.saving': 'Kaydediliyor...',
    'membership.plans.active': 'Aktif',
    'membership.plans.inactive': 'Pasif',
    'membership.plans.delete.plan': 'Planı Sil',
    'membership.plans.confirm.delete': 'Bu planı silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    'membership.plans.delete': 'Sil',
    'membership.plans.no.plans.found': 'Plan bulunamadı',
    'membership.plans.create.first.plan': 'İlk planınızı oluşturun',
    'membership.plans.benefits.title': 'Avantajlar:',
    'membership.plans.active.subscriptions': 'Aktif',
    'membership.plans.total.subscriptions': 'Toplam',
    'membership.plans.limit': 'Limit',
    
    // Career Center
    'career.title': 'Kariyer Merkezi',
    'career.jobs': 'İş İlanları',
    'career.apply': 'Başvur',
    'career.saved': 'Kaydedilen İşler',
    'career.applications': 'Başvurularım',
    'career.job.title': 'İş Unvanı',
    'career.company': 'Şirket',
    'career.location': 'Konum',
    'career.salary': 'Maaş',
    'career.type': 'İş Türü',
    'career.description': 'Açıklama',
    'career.requirements': 'Gereksinimler',
    'career.choose.role': 'Başlamak için rolünüzü seçin',
    'career.job.seeker': 'İş Arayan',
    'career.employer': 'İşveren',
    
    // Career Individual Dashboard
    'career.individual.browse.jobs': 'İşleri Gözat',
    'career.individual.my.applications': 'Başvurularım',
    'career.individual.saved.jobs': 'Kaydedilen İşler',
    'career.individual.career.profile': 'Kariyer Profili',
    'career.individual.select.page': 'Sayfa Seç',
    
    // Career Company Dashboard
    'career.company.job.postings': 'İş İlanları',
    'career.company.applications': 'Başvurular',
    'career.company.analytics': 'Analitik',
    'career.company.select.page': 'Sayfa Seç',
    'career.company.actions': 'İşlemler',
    'career.company.job.status': 'İş Durumu',
    'career.company.activate.job': 'İşi Aktifleştir',
    'career.company.activate.job.desc': 'İşi adaylara görünür yap',
    'career.company.pause.job': 'İşi Duraklat',
    'career.company.pause.job.desc': 'Geçici olarak adaylardan gizle',
    'career.company.close.job': 'İşi Kapat',
    'career.company.close.job.desc': 'Başvuru kabul etmeyi durdur',
    'career.company.edit.job.details': 'İş Detaylarını Düzenle',
    'career.company.view.applications': 'Başvuruları Görüntüle',
    'career.company.edit.job.posting': 'İş İlanını Düzenle',
    'career.company.create.new.job.posting': 'Yeni İş İlanı Oluştur',
    'career.company.cancel': 'İptal',
    'career.company.loading.jobs': 'İş ilanlarınız yükleniyor...',
    'career.company.no.job.postings': 'Henüz iş ilanı yok',
    'career.company.create.first.job': 'Başlamak için ilk iş ilanınızı oluşturun.',
    'career.company.post.job': 'İş İlanı Ver',
    'career.company.your.job.postings': 'İş İlanlarınız ({count} aktif)',
    'career.company.post.new.job': 'Yeni İş İlanı Ver',
    'career.company.posted': 'Yayınlandı',
    'career.company.applications': 'başvuru',
    'career.company.remote': 'Uzaktan',
    'career.company.salary.not.specified': 'Maaş belirtilmemiş',
    'career.company.previous': 'Önceki',
    'career.company.next': 'Sonraki',
    'career.company.filter.by.status': 'Duruma Göre Filtrele',
    'career.company.all.status': 'Tüm Durumlar',
    'career.company.pending': 'Beklemede',
    'career.company.reviewing': 'İnceleniyor',
    'career.company.interview': 'Mülakat',
    'career.company.accepted': 'Kabul Edildi',
    'career.company.rejected': 'Reddedildi',
    'career.company.filter.by.job': 'İşe Göre Filtrele',
    'career.company.all.jobs': 'Tüm İşler',
    'career.company.loading.applications': 'Başvurular yükleniyor...',
    'career.company.no.applications': 'Henüz başvuru yok',
    'career.company.applications.desc': 'İş ilanlarınız için başvurular burada görünecek.',
    'career.company.applied.for': 'Başvurulan',
    'career.company.email': 'E-posta',
    'career.company.applied': 'Başvuruldu',
    'career.company.cover.letter': 'Ön Yazı',
    'career.company.notes': 'Notlar',
    'career.company.view.resume': 'Özgeçmişi Görüntüle',
    
    // Users
    'users.title': 'Kişiler',
    'users.search': 'Kişi Ara',
    'users.follow': 'Takip Et',
    'users.unfollow': 'Takipten Çık',
    'users.message': 'Mesaj',
    'users.connect': 'Bağlan',
    'users.mutual.connections': 'Ortak Bağlantılar',
    
    // Common
    'common.loading': 'Yükleniyor...',
    'common.error': 'Hata',
    'common.success': 'Başarılı',
    'common.cancel': 'İptal',
    'common.save': 'Kaydet',
    'common.edit': 'Düzenle',
    'common.delete': 'Sil',
    'common.view': 'Görüntüle',
    'common.add': 'Ekle',
    'common.search': 'Ara',
    'common.filter': 'Filtrele',
    'common.export': 'Dışa Aktar',
    'common.import': 'İçe Aktar',
    'common.submit': 'Gönder',
    'common.back': 'Geri',
    'common.next': 'İleri',
    'common.previous': 'Önceki',
    'common.close': 'Kapat',
    'common.open': 'Aç',
    'common.yes': 'Evet',
    'common.no': 'Hayır',
    'common.confirm': 'Onayla',
    'common.required': 'Gerekli',
    'common.optional': 'Opsiyonel',
    
    // Membership Application
    'membership.apply.title': 'Üyelik Başvurusu',
    'membership.apply.organization': 'Organizasyon',
    'membership.apply.fee': 'Ücret',
    'membership.apply.application.fee': 'Başvuru Ücreti',
    'membership.apply.form.not.available': 'Form Mevcut Değil',
    'membership.apply.form.not.available.desc': 'Bu üyelik için başvuru formu şu anda mevcut değil.',
    'membership.apply.plan.creator.error': 'Oluşturduğunuz bir plana başvuru yapamazsınız. Plan oluşturucuları otomatik olarak üye sayılır.',
    'membership.apply.select.field': '{field} Seçin',
    'membership.apply.enter.field': '{field} Girin',
    
    // Plan Details
    'plan.details.title': 'Plan Detayları',
    'plan.details.description': 'Açıklama',
    'plan.details.benefits': 'Avantajlar',
    'plan.details.renewal.interval': 'Yenileme Aralığı',
    'plan.details.status': 'Durum',
    'plan.details.max.members': 'Maksimum Üye',
    'plan.details.active': 'Aktif',
    'plan.details.inactive': 'Pasif',
    'plan.details.free': 'Ücretsiz',
    'plan.details.per.month': 'aylık',
    'plan.details.per.quarter': 'çeyrek yıllık',
    'plan.details.per.year': 'yıllık',
    'plan.details.one.time': 'tek seferlik',
    'plan.details.no.description': 'Açıklama mevcut değil.',
    
    // Navigation
    'nav.language': 'Dil',
    
    // Applications
    'applications.title': 'Üyelik Başvuruları',
    'applications.loading': 'Başvurular yükleniyor...',
    'applications.search.placeholder': 'Ad, e-posta ile ara...',
    'applications.all.statuses': 'Tüm Durumlar',
    'applications.pending': 'Beklemede',
    'applications.approved': 'Onaylandı',
    'applications.rejected': 'Reddedildi',
    'applications.date.applied': 'Başvuru Tarihi',
    'applications.name': 'Ad',
    'applications.email': 'E-posta',
    'applications.phone': 'Telefon',
    'applications.plan': 'Plan',
    'applications.student.id': 'Öğrenci No',
    'applications.status': 'Durum',
    'applications.actions': 'İşlemler',
    'applications.approve': 'Onayla',
    'applications.reject': 'Reddet',
    'applications.view': 'Görüntüle',
    'applications.delete': 'Sil',
    'applications.no.applications': 'Başvuru bulunamadı',
    'applications.join.organization': 'Organizasyona Katıl',
    'applications.join.description': 'Üyelik başvurularını görüntülemek için bir organizasyonun üyesi olmanız gerekiyor.',
    'applications.no.organizations': 'Katılabilecek organizasyon yok.',
    'applications.visit.website': 'Web Sitesini Ziyaret Et',
    'applications.join.organization.button': 'Organizasyona Katıl',
    'applications.joining': 'Katılıyor...',
    'applications.successfully.joined': 'Organizasyona başarıyla katıldınız! Artık başvuruları görüntüleyebilirsiniz.',
    'applications.error.joining': 'Organizasyona katılırken hata: {error}',
    'applications.view.details': 'Başvuru Detaylarını Görüntüle',
    'applications.approve.application': 'Başvuruyu Onayla',
    'applications.reject.application': 'Başvuruyu Reddet',
    'applications.basic.information': 'Temel Bilgiler',
    'applications.not.provided': 'Belirtilmemiş',
    'applications.custom.form.data': 'Özel Form Verileri',
    'applications.payment.information': 'Ödeme Bilgileri',
    'applications.payment.method': 'Ödeme Yöntemi',
    'applications.amount': 'Tutar',
    'applications.transaction.id': 'İşlem No',
    'applications.processed': 'İşlendi',
    'applications.approval.notes': 'Onay Notları (Opsiyonel)',
    'applications.rejection.notes': 'Red Notları (Opsiyonel)',
    'applications.add.notes': 'Bu {type} hakkında not ekle...',
    'applications.notes.help': 'Notlar başvuru ile birlikte kaydedilecek ve daha sonra görüntülenebilecek.',
    'applications.action': 'İşlem',
    'applications.approve.and.create': '{name} için başvuruyu onayla ve kullanıcı hesabı oluştur',
    'applications.reject.application.for': '{name} için başvuruyu reddet',
    'applications.close': 'Kapat',
    'applications.cancel': 'İptal',
    'applications.approve.application.button': 'Başvuruyu Onayla',
    'applications.reject.application.button': 'Başvuruyu Reddet',
    'applications.page': 'Sayfa {current} / {total}',
    
    // Payments
    'payments.title': 'Ödemeler',
    'payments.add.payment': 'Ödeme Ekle',
    'payments.loading': 'Ödemeler yükleniyor...',
    'payments.search.placeholder': 'Ad, referans numarası ile ara...',
    'payments.all.statuses': 'Tüm Durumlar',
    'payments.completed': 'Tamamlandı',
    'payments.failed': 'Başarısız',
    'payments.refunded': 'İade Edildi',
    'payments.payment.date': 'Ödeme Tarihi',
    'payments.full.name': 'Ad Soyad',
    'payments.payment.method': 'Ödeme Yöntemi',
    'payments.identifier': 'Tanımlayıcı',
    'payments.reference.number': 'Referans No',
    'payments.edit.payment': 'Ödemeyi Düzenle',
    'payments.delete.payment': 'Ödemeyi Sil',
    'payments.no.payments': 'Ödeme bulunamadı',
    'payments.edit.payment.modal': 'Ödemeyi Düzenle',
    'payments.add.payment.modal': 'Ödeme Ekle',
    'payments.user': 'Kullanıcı',
    'payments.select.user': 'Kullanıcı Seç',
    'payments.select.plan': 'Plan Seç',
    'payments.payment.date.label': 'Ödeme Tarihi',
    'payments.identifier.placeholder': 'İşlem No',
    'payments.reference.number.placeholder': 'Referans numarası',
    'payments.notes': 'Notlar',
    'payments.additional.notes': 'Ek notlar...',
    'payments.save.payment': 'Ödemeyi Kaydet',
    'payments.saving': 'Kaydediliyor...',
    'payments.error.saving': 'Ödeme kaydedilirken hata: {error}',
    'payments.error.deleting': 'Ödeme silinirken hata: {error}',
    'payments.confirm.delete': 'Bu ödemeyi silmek istediğinizden emin misiniz?',
    'payments.cash': 'Nakit',
    'payments.bank.transfer': 'Banka Havalesi',
    'payments.credit.card': 'Kredi Kartı',
    'payments.debit.card': 'Banka Kartı',
    'payments.mobile.payment': 'Mobil Ödeme',
    'payments.other': 'Diğer',
    
    // Scheduled Payments
    'scheduled.payments.title': 'Planlanmış Ödemeler',
    'scheduled.payments.add': 'Planlanmış Ödeme Ekle',
    'scheduled.payments.loading': 'Planlanmış ödemeler yükleniyor...',
    'scheduled.payments.no.payments': 'Planlanmış ödeme yapılandırılmamış',
    'scheduled.payments.create.first': 'İlk Planlanmış Ödemenizi Oluşturun',
    'scheduled.payments.scheduled.date': 'Planlanan Tarih',
    'scheduled.payments.frequency': 'Sıklık',
    'scheduled.payments.one.time': 'Tek Seferlik',
    'scheduled.payments.monthly': 'Aylık',
    'scheduled.payments.quarterly': 'Çeyrek Yıllık',
    'scheduled.payments.yearly': 'Yıllık',
    'scheduled.payments.delete.title': 'Planlanmış ödemeyi sil',
    'scheduled.payments.add.modal': 'Planlanmış Ödeme Ekle',
    'scheduled.payments.amount': 'Tutar',
    'scheduled.payments.scheduled.date.time': 'Planlanan Tarih ve Saat',
    'scheduled.payments.description': 'Açıklama',
    'scheduled.payments.description.placeholder': 'Ödeme açıklamasını girin...',
    'scheduled.payments.associated.plan': 'İlişkili Plan (Opsiyonel)',
    'scheduled.payments.select.plan': 'Plan seçin',
    'scheduled.payments.cancel': 'İptal',
    'scheduled.payments.create': 'Planlanmış Ödeme Oluştur',
    'scheduled.payments.creating': 'Oluşturuluyor...',
    'scheduled.payments.confirm.delete': 'Bu planlanmış ödemeyi silmek istediğinizden emin misiniz?',
    
    // Debts
    'debts.title': 'Borçlar ve Bekleyen Bakiyeler',
    'debts.total.outstanding': 'Toplam Bekleyen',
    'debts.add.debt': 'Borç Ekle',
    'debts.loading': 'Borçlar yükleniyor...',
    'debts.no.debts': 'Kayıtlı borç yok',
    'debts.add.first.debt': 'İlk Borcunuzu Ekleyin',
    'debts.issued.on': 'Verilme Tarihi',
    'debts.type': 'Tür',
    'debts.subscription': 'Abonelik',
    'debts.fee': 'Ücret',
    'debts.penalty': 'Ceza',
    'debts.other': 'Diğer',
    'debts.outstanding': 'Bekleyen',
    'debts.paid': 'Ödendi',
    'debts.written.off': 'Silindi',
    'debts.manual.entry': 'Manuel',
    'debts.mark.as.paid': 'Ödendi olarak işaretle',
    'debts.write.off': 'Sil',
    'debts.delete.debt': 'Borcu sil',
    'debts.add.modal': 'Yeni Borç Ekle',
    'debts.amount': 'Tutar',
    'debts.description': 'Açıklama',
    'debts.description.placeholder': 'Borç açıklamasını girin...',
    'debts.debt.type': 'Borç Türü',
    'debts.issue.date': 'Verilme Tarihi',
    'debts.manual.entry.label': 'Manuel Giriş',
    'debts.manual.entry.help': 'Bu borcun otomatik olarak oluşturulmak yerine manuel olarak girildiğini işaretleyin',
    'debts.cancel': 'İptal',
    'debts.create.debt': 'Borç Oluştur',
    'debts.creating': 'Oluşturuluyor...',
    'debts.confirm.delete': 'Bu borcu silmek istediğinizden emin misiniz?',
    
    // Reminders
    'reminders.title': 'Hatırlatıcılar ve Bildirimler',
    'reminders.add.reminder': 'Hatırlatıcı Ekle',
    'reminders.loading': 'Hatırlatıcılar yükleniyor...',
    'reminders.no.reminders': 'Yapılandırılmış hatırlatıcı yok',
    'reminders.create.first': 'İlk Hatırlatıcınızı Oluşturun',
    'reminders.scheduled': 'Planlanan',
    'reminders.recipient': 'Alıcı',
    'reminders.send.now': 'Şimdi gönder',
    'reminders.delete.reminder': 'Hatırlatıcıyı sil',
    'reminders.add.modal': 'Yeni Hatırlatıcı Ekle',
    'reminders.reminder.name': 'Hatırlatıcı Adı',
    'reminders.reminder.name.placeholder': 'Hatırlatıcı adını girin...',
    'reminders.reminder.type': 'Hatırlatıcı Türü',
    'reminders.renewal.reminder': 'Yenileme Hatırlatıcısı',
    'reminders.payment.due': 'Ödeme Vadesi',
    'reminders.overdue.notice': 'Vadesi Geçmiş Bildirimi',
    'reminders.welcome.message': 'Hoş Geldin Mesajı',
    'reminders.custom.reminder': 'Özel Hatırlatıcı',
    'reminders.reminder.date.time': 'Hatırlatıcı Tarihi ve Saati',
    'reminders.message': 'Mesaj',
    'reminders.message.placeholder': 'Hatırlatıcı mesajını girin...',
    'reminders.cancel': 'İptal',
    'reminders.create.reminder': 'Hatırlatıcı Oluştur',
    'reminders.creating': 'Oluşturuluyor...',
    'reminders.confirm.delete': 'Bu hatırlatıcıyı silmek istediğinizden emin misiniz?',
    
    // Membership Settings
    'settings.title': 'Üyelik Ayarları',
    'settings.general.settings': 'Genel Ayarlar',
    'settings.auto.approve': 'Başvuruları otomatik onayla',
    'settings.enable.form': 'Başvuru formunu etkinleştir',
    'settings.allow.bank.transfers': 'Banka havalelerine izin ver',
    'settings.invoice.text': 'Fatura Metni',
    'settings.invoice.text.placeholder': 'Faturalarda görünecek özel metin...',
    'settings.email.notifications': 'E-posta Bildirimleri',
    'settings.new.application.notifications': 'Yeni başvuru bildirimleri',
    'settings.payment.received.notifications': 'Ödeme alındı bildirimleri',
    'settings.subscription.expiring.notifications': 'Abonelik süresi doluyor bildirimleri',
    'settings.save.settings': 'Ayarları Kaydet',
    'settings.saved.successfully': 'Ayarlar başarıyla kaydedildi!',
    
    // Coupons
    'coupons.title': 'Kuponlar ve İndirimler',
    'coupons.add.coupon': 'Kupon Ekle',
    'coupons.loading': 'Kuponlar yükleniyor...',
    'coupons.no.coupons': 'Yapılandırılmış kupon yok',
    'coupons.create.first': 'İlk Kuponunuzu Oluşturun',
    'coupons.discount': 'İndirim',
    'coupons.redemptions': 'Kullanımlar',
    'coupons.expires': 'Biter',
    'coupons.no.expiry': 'Süresiz',
    'coupons.activate': 'Aktifleştir',
    'coupons.deactivate': 'Pasifleştir',
    'coupons.delete.coupon': 'Kuponu sil',
    'coupons.add.modal': 'Yeni Kupon Ekle',
    'coupons.coupon.name': 'Kupon Adı',
    'coupons.coupon.name.placeholder': 'Kupon adını girin...',
    'coupons.coupon.code': 'Kupon Kodu',
    'coupons.coupon.code.placeholder': 'Kupon kodunu girin...',
    'coupons.generate': 'Oluştur',
    'coupons.discount.amount': 'İndirim Tutarı',
    'coupons.discount.type': 'İndirim Türü',
    'coupons.percentage': 'Yüzde (%)',
    'coupons.fixed.amount': 'Sabit Tutar ($)',
    'coupons.max.redemptions': 'Maksimum Kullanım',
    'coupons.max.redemptions.placeholder': 'Sınırsız için boş bırakın',
    'coupons.max.redemptions.help': 'Sınırsız kullanım için boş bırakın',
    'coupons.expiry.date': 'Bitiş Tarihi',
    'coupons.expiry.date.help': 'Süresiz için boş bırakın',
    'coupons.cancel': 'İptal',
    'coupons.create.coupon': 'Kupon Oluştur',
    'coupons.creating': 'Oluşturuluyor...',
    'coupons.confirm.delete': 'Bu kuponu silmek istediğinizden emin misiniz?',
    'coupons.inactive': 'Pasif',
    'coupons.expired': 'Süresi Dolmuş',
    'coupons.maxed.out': 'Limit Dolmuş',
    'coupons.active': 'Aktif',
    
    // Application Forms
    'forms.title': 'Başvuru Formları',
    'forms.create.form': 'Form Oluştur',
    'forms.loading': 'Başvuru formları yükleniyor...',
    'forms.join.organization': 'Organizasyona Katıl',
    'forms.join.description': 'Başvuru formları oluşturmak ve yönetmek için bir organizasyona katılmanız gerekiyor.',
    'forms.no.organizations': 'Katılabilecek organizasyon yok.',
    'forms.join.organization.button': 'Organizasyona Katıl',
    'forms.joining': 'Katılıyor...',
    'forms.failed.to.join': 'Organizasyona katılırken hata: {error}',
    'forms.view.form': 'Formu Görüntüle',
    'forms.edit.form': 'Formu Düzenle',
    'forms.unpublish.form': 'Formu Yayından Kaldır',
    'forms.publish.form': 'Formu Yayınla',
    'forms.delete.form': 'Formu Sil',
    'forms.fields': 'Alanlar',
    'forms.created': 'Oluşturuldu',
    'forms.updated': 'Güncellendi',
    'forms.form.fields': 'Form Alanları',
    'forms.more': 'daha fazla',
    'forms.no.forms': 'Başvuru formu bulunamadı',
    'forms.create.first': 'İlk formunuzu oluşturun',
    'forms.edit.modal': 'Formu Düzenle',
    'forms.create.modal': 'Form Oluştur',
    'forms.form.title': 'Form Başlığı',
    'forms.form.title.placeholder': 'örn., Spor Salonu Üyelik Başvurusu',
    'forms.description': 'Açıklama',
    'forms.description.placeholder': 'Form açıklaması...',
    'forms.cancel': 'İptal',
    'forms.save.form': 'Formu Kaydet',
    'forms.saving': 'Kaydediliyor...',
    'forms.error.saving': 'Form kaydedilirken hata: {error}',
    'forms.error.deleting': 'Form silinirken hata: {error}',
    'forms.error.publishing': 'Form yayınlanırken hata: {error}',
    'forms.error.unpublishing': 'Form yayından kaldırılırken hata: {error}',
    'forms.confirm.delete': 'Bu formu silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    'forms.published': 'Yayınlandı',
    'forms.draft': 'Taslak',
    'forms.view.modal.title': 'Başvuru Formunu Görüntüle: {title}',
    'forms.close': 'Kapat',
    'forms.description.section': 'Açıklama',
    'forms.status.section': 'Durum',
    'forms.fields.section': 'Form Alanları ({count})',
    'forms.no.fields': 'Bu form için tanımlanmış alan yok.',
    'forms.form.information': 'Form Bilgileri',
    'forms.created.label': 'Oluşturuldu',
    'forms.last.updated': 'Son Güncelleme',
    'forms.organization': 'Organizasyon',
    'forms.edit.form.button': 'Formu Düzenle',
    'forms.required': 'Zorunlu',
    'forms.placeholder': 'Yer tutucu: {placeholder}',
    'forms.options': 'Seçenekler: {options}',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Get language from localStorage or default to English
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    // Save language preference to localStorage
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key, params = {}) => {
    let translation = translations[language]?.[key] || translations.en[key] || key;
    
    // Replace parameters in translation
    Object.keys(params).forEach(param => {
      translation = translation.replace(`{${param}}`, params[param]);
    });
    
    return translation;
  };

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage);
  };

  const value = {
    language,
    changeLanguage,
    t,
    availableLanguages: [
      { code: 'en', name: 'English', nativeName: 'English' },
      { code: 'tr', name: 'Turkish', nativeName: 'Türkçe' }
    ]
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
